// Write src/generated/engines.ts, the list of rule engines the function
// bundles (SPEC §4 step 4): always the repository's own engine
// (packages/engine) with its rule pack, and optionally the engine and pack of
// the rules release before it, so pages loaded before a rules release keep
// working until the site's explain.json catches up.
//
// Usage:
//   node scripts/gen-engines.mjs                     current engine only
//   node scripts/gen-engines.mjs --previous auto     also the previous rules release,
//                                                    found in git history (needs a full clone)
//   node scripts/gen-engines.mjs --previous <ref>    also the engine and pack at <ref>
//
// The previous engine is copied out of git into .previous/ (not committed),
// and its own gen-pack.mjs writes its pack module there. Nothing is fetched
// from the network.

import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { generate } from "../../engine/scripts/gen-pack.mjs";

const PACKAGE = fileURLToPath(new URL("..", import.meta.url));
const ROOT = join(PACKAGE, "..", "..");
const OUT = join(PACKAGE, "src", "generated", "engines.ts");
const PREVIOUS_DIR = join(PACKAGE, ".previous");
const PACK = "rules/biasclear-rules.json";

function git(args, options = {}) {
  const r = spawnSync("git", args, { cwd: ROOT, encoding: options.encoding ?? "utf8", maxBuffer: 64 * 1024 * 1024 });
  if (r.status !== 0) throw new Error(`git ${args[0]} failed: ${(r.stderr || "").toString().trim()}`);
  return r.stdout;
}

function versionAt(ref) {
  try {
    return JSON.parse(git(["show", `${ref}:${PACK}`])).rules_version;
  } catch {
    return undefined;
  }
}

/** The newest commit whose rule pack has a different rules_version from the working tree's. */
export function findPreviousRelease() {
  const current = JSON.parse(readFileSync(join(ROOT, PACK), "utf8")).rules_version;
  if (git(["rev-parse", "--is-shallow-repository"]).trim() === "true") {
    throw new Error("--previous auto needs the full git history (actions/checkout with fetch-depth: 0)");
  }
  for (const sha of git(["log", "--format=%H", "--", PACK]).split("\n").filter(Boolean)) {
    const v = versionAt(sha);
    if (v !== undefined && v !== current) {
      const hasEngine = spawnSync("git", ["cat-file", "-e", `${sha}:packages/engine/src/index.ts`], { cwd: ROOT }).status === 0;
      return hasEngine ? { ref: sha, version: v } : undefined;
    }
  }
  return undefined;
}

function extractPrevious(ref) {
  const version = versionAt(ref);
  if (version === undefined) throw new Error(`no rule pack at ${ref}`);
  const dir = join(PREVIOUS_DIR, version.replace(/[^A-Za-z0-9._-]/g, "_"));
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  const paths = ["packages/engine/src", "packages/engine/scripts/gen-pack.mjs", PACK];
  const tar = spawnSync("git", ["archive", "--format=tar", ref, ...paths], { cwd: ROOT, maxBuffer: 64 * 1024 * 1024 });
  if (tar.status !== 0) throw new Error(`git archive ${ref} failed`);
  const untar = spawnSync("tar", ["-x", "-C", dir], { input: tar.stdout });
  if (untar.status !== 0) throw new Error("could not unpack the previous engine");
  const gen = spawnSync(process.execPath, [join(dir, "packages/engine/scripts/gen-pack.mjs")], { encoding: "utf8" });
  if (gen.status !== 0) throw new Error(`the previous engine's gen-pack failed: ${gen.stderr}`);
  return { version, entry: join(dir, "packages/engine/src/index.js") };
}

export function generateEngines(previous = "none") {
  const { rulesVersion } = generate();
  const entries = [{ version: rulesVersion, entry: join(ROOT, "packages/engine/src/index.js") }];
  rmSync(PREVIOUS_DIR, { recursive: true, force: true });
  let prev;
  if (previous === "auto") {
    const found = findPreviousRelease();
    if (found) prev = extractPrevious(found.ref);
  } else if (previous && previous !== "none") {
    prev = extractPrevious(previous);
  }
  if (prev) {
    if (prev.version === rulesVersion) throw new Error(`the previous release has the same rules_version (${rulesVersion})`);
    entries.push(prev);
  }
  const rel = (p) => {
    const r = relative(dirname(OUT), p).split("\\").join("/");
    return r.startsWith(".") ? r : `./${r}`;
  };
  const source =
    "// Generated by scripts/gen-engines.mjs. Do not edit; not committed.\n" +
    "// The first module is the repository's own engine (the current rules release).\n\n" +
    entries.map((e, i) => `import * as engine${i} from ${JSON.stringify(rel(e.entry))};`).join("\n") +
    "\n\nexport const ENGINE_MODULES = [" +
    entries.map((_, i) => `engine${i}`).join(", ") +
    "] as const;\n";
  mkdirSync(dirname(OUT), { recursive: true });
  let current = null;
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    // not generated yet
  }
  if (current !== source) writeFileSync(OUT, source);
  return entries.map((e) => e.version);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const i = process.argv.indexOf("--previous");
  const previous = i >= 0 ? process.argv[i + 1] : process.env.EXPLAIN_PREVIOUS ?? "none";
  try {
    const versions = generateEngines(previous);
    console.log(`src/generated/engines.ts: rules ${versions.join(", ")}`);
  } catch (err) {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  }
}
