// Read rules/biasclear-rules.json (the single source of truth) and write
// src/generated/pack.ts, which holds the pack in RFC 8785 canonical JSON and
// its SHA-256. The generated file is not committed; every build, typecheck
// and test run makes it again.
//
// The hash is computed here, at build time, with node:crypto, so that scan()
// can stay synchronous in the browser (Web Crypto's digest is async).
// test/hash.test.ts recomputes it at test time with Web Crypto
// (crypto.subtle.digest) and with node:crypto, and scripts/parity.mjs checks
// it against Python's rules_hash.
//
// Usage: node scripts/gen-pack.mjs

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE = fileURLToPath(new URL("..", import.meta.url));
const ROOT = join(PACKAGE, "..", "..");
export const PACK_PATH = join(ROOT, "rules", "biasclear-rules.json");
const OUT = join(PACKAGE, "src", "generated", "pack.ts");

/**
 * RFC 8785 canonical JSON. Python's canonical_json (sorted keys, no spaces,
 * ensure_ascii=False) writes the same bytes for values made only of strings,
 * safe integers, booleans, null, arrays and objects with ASCII keys, so
 * checkValue() rejects anything else.
 */
export function canonicalJson(value) {
  if (Array.isArray(value)) return "[" + value.map(canonicalJson).join(",") + "]";
  if (value !== null && typeof value === "object") {
    return (
      "{" +
      Object.keys(value)
        .sort()
        .map((k) => JSON.stringify(k) + ":" + canonicalJson(value[k]))
        .join(",") +
      "}"
    );
  }
  return JSON.stringify(value);
}

function checkValue(value, path) {
  if (Array.isArray(value)) {
    value.forEach((v, i) => checkValue(v, `${path}[${i}]`));
  } else if (value !== null && typeof value === "object") {
    for (const [k, v] of Object.entries(value)) {
      if (!/^[\x20-\x7e]*$/.test(k)) throw new Error(`${path}: non-ASCII key ${JSON.stringify(k)}`);
      checkValue(v, `${path}.${k}`);
    }
  } else if (typeof value === "number") {
    if (!Number.isSafeInteger(value)) throw new Error(`${path}: ${value} is not a safe integer`);
  } else if (typeof value === "string") {
    if (/[\uD800-\uDFFF]/u.test(value)) throw new Error(`${path}: lone surrogate`);
  } else if (typeof value !== "boolean" && value !== null) {
    throw new Error(`${path}: unexpected ${typeof value}`);
  }
}

/** The shape the engine reads; rules/schema.json and the Python tests check the rest. */
function checkShape(pack) {
  const fail = (msg) => {
    throw new Error(`rule pack: ${msg}`);
  };
  if (typeof pack.rules_version !== "string") fail("rules_version must be a string");
  const cs = pack.citation_suppression;
  if (!cs || !Number.isSafeInteger(cs.window) || cs.window < 0) fail("citation_suppression.window");
  if (!["", "i", "s", "is"].includes(cs.flags)) fail("citation_suppression.flags");
  if (!Array.isArray(cs.patterns) || cs.patterns.some((p) => typeof p !== "string")) fail("citation_suppression.patterns");
  if (!Array.isArray(pack.rules) || pack.rules.length === 0) fail("rules");
  for (const r of pack.rules) {
    const where = `rule ${JSON.stringify(r.id)}`;
    if (typeof r.id !== "string" || typeof r.name !== "string") fail(`${where}: id and name`);
    if (![1, 2, 3].includes(r.pit_tier)) fail(`${where}: pit_tier`);
    if (!["general", "legal", "media", "financial"].includes(r.domain)) fail(`${where}: domain`);
    if (!["low", "moderate", "high", "critical"].includes(r.severity)) fail(`${where}: severity`);
    if (!Array.isArray(r.indicators) || r.indicators.length === 0) fail(`${where}: indicators`);
    if (!Number.isSafeInteger(r.min_matches) || r.min_matches < 1) fail(`${where}: min_matches`);
    if (typeof r.suppress_if_cited !== "boolean") fail(`${where}: suppress_if_cited`);
    if (!["", "i", "s", "is"].includes(r.flags)) fail(`${where}: flags`);
  }
}

export function generate() {
  const pack = JSON.parse(readFileSync(PACK_PATH, "utf8"));
  checkValue(pack, "pack");
  checkShape(pack);
  const canonical = canonicalJson(pack);
  const hash = createHash("sha256").update(canonical, "utf8").digest("hex");
  const source =
    "// Generated by scripts/gen-pack.mjs from rules/biasclear-rules.json. Do not edit.\n" +
    "// Not committed: every build, typecheck and test run writes it again.\n\n" +
    `/** SHA-256 of PACK_JSON (the pack in RFC 8785 canonical JSON, UTF-8), hex. */\n` +
    `export const RULES_HASH: string = ${JSON.stringify(hash)};\n\n` +
    `/** rules/biasclear-rules.json in RFC 8785 canonical JSON. */\n` +
    `export const PACK_JSON: string = ${JSON.stringify(canonical)};\n`;
  mkdirSync(dirname(OUT), { recursive: true });
  let current = null;
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    // not generated yet
  }
  if (current !== source) writeFileSync(OUT, source);
  return { hash, rulesVersion: pack.rules_version, out: relative(PACKAGE, OUT) };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { hash, rulesVersion, out } = generate();
  console.log(`${out}: rules ${rulesVersion}, rules hash ${hash}`);
}
